### ISSUE TITLE
Unclear on how to configure for non-default ns

### ISSUE THREAD

**Issue by yhekma** [instaclustr/cassandra-operator#110]
Since https://github.com/instaclustr/cassandra-operator/pull/103 was merged, support for namespaces other than `default` should be there. I am however not clear on how to configure it. It doesn't seem to work "out of the box" (ie. the operator watches the ns that it is configured in) or maybe I am doing something wrong? I just deployed the operator and cassandra with default values in a namespace called `cassandra` and while the `cassandra-datacenters.stable.instaclustr.com` gets created, the `cassandra-clusters.stable.instaclustr.com` does not.

**Comment by benbromhead** [comment]
Hi @yhekma 

Apologies we haven't updated documentation for namespace support. The way it's implemented is actually the namespace the operator will watch for changes to CRD / operator manage resources. This is not an optimal way to do so (we should watch all namespaces... maybe), but its the implementation as it stands.

To changes the namespace the operator watches (it can be deployed in a different namespace if you want), you will need to modify the deployment the operator gets deployed by (either the helm package or the example yaml) to include the following in the containers spec:

```yaml
command: ["java"]
args: ["-jar", "/opt/cassandra-operator/operator-1.0.jar", "--namespace=NAMESPACE"]
```

The modified helm package (helm/cassandra-operator/templates/deployment.yaml) would look like:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "cassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    operator: cassandra
    release: {{ .Release.Name }}
  name: {{ template "cassandra-operator.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "cassandra-operator.name" . }}
        operator: cassandra
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ template "cassandra-operator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["java"]
          args: ["-jar", "/opt/cassandra-operator/operator-1.0.jar", "--namespace=NAMESPACE"]
          ports:
            - containerPort: 8080
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "cassandra-operator.fullname" . }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}

```
