### ISSUE TITLE
Unable to create cluster in different namespace

### ISSUE THREAD

**Issue by zwennesm** [instaclustr/cassandra-operator#122]
Hi everyone,

I'm not 100% sure if the issue is cluster related or cassandra-operator related but it seems that when deploying a cluster to another namespace, the cassandra-operator is unable to create a Statefullset and pods. 

Cluster details:
```
version: v1.11.5-gke.4
rbac enabled: true
```
When i describe the newly created `CRD` it gives me the following response:

```
➜ kubectl describe cassandra-datacenters.stable.instaclustr.com -n other-namespace
Spec:
  Cassandra Image:  gcr.io/cassandra-operator/cassandra:latest
  Data Volume Claim:
    Access Modes:
      ReadWriteOnce
    Resources:
      Requests:
        Storage:         100Mi
  Image Pull Policy:     IfNotPresent
  Privileged Supported:  true
  Prometheus Support:    false
  Replicas:              3
  Resources:
    Limits:
      Memory:  1Gi
    Requests:
      Memory:     1Gi
  Sidecar Image:  gcr.io/cassandra-operator/cassandra-sidecar:latest
Events:           <none>
```
For some reason no events are being triggered. And i am unable to see where it fails. Any ideas?

**Script used to re-produce the issue**
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cassandra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cassandra-operator
subjects:
- kind: ServiceAccount
  name: cassandra-operator
  namespace: other-namespace
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cassandra-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - stable.instaclustr.com
  resources:
  - cassandra-cluster
  - cassandra-clusters
  - cassandra-datacenter
  - cassandra-datacenters
  - cassandra-backup
  - cassandra-backups
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - pods
  verbs: ['list', 'delete']
- apiGroups: ['']
  resources:
  - services
  - endpoints
  verbs: ['get', 'create', 'update']
- nonResourceURLs: ["/version", "/version/*"]
  verbs: ['get']
- apiGroups: ['']
  resources:
  - nodes
  verbs: ['list', 'watch']
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['*']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cassandra-operator
  namespace: other-namespace
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: cassandra-operator
  name: cassandra-operator
  namespace: other-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cassandra-operator
  template:
    metadata:
      labels:
        k8s-app: cassandra-operator
    spec:
      containers:
      - image: gcr.io/cassandra-operator/cassandra-operator:latest
        name: cassandra-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
      serviceAccountName: cassandra-operator
---
apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: cassandra-dev
  namespace: other-namespace
spec:
  replicas: 3
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  cassandraImage: "gcr.io/cassandra-operator/cassandra:latest"
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  privilegedSupported: true
  prometheusSupport: false
```
