### ISSUE TITLE
Review required fields in CassandraDataCenterSpec

### ISSUE THREAD

**Issue by johananl** [instaclustr/cassandra-operator#270]
https://github.com/instaclustr/cassandra-operator/blob/810511b1d25a96524c5cb3abe22160ed0f21908c/pkg/apis/cassandraoperator/v1alpha1/cassandradatacenter_types.go#L13-L31

With simplicity and ease of use in mind (especially for first-time users who want to evaluate the operator), it seems to me like at least some of the fields above should be optional with some sane default. Examples:

- `ImagePullPolicy` - is it actually necessary for a user (i.e. not a developer) to think about this?
- `Resources` - shouldn't we provide an opinionated default here, and allow the user to override?
- `DataVolumeClaimSpec` - do we really need to expose the whole YAML snippet? Feels like boilerplate to me. Since the "interesting" field is `storage`, we could ask just for that (and even provide a default!).
- `PrometheusSupport` - is it actually necessary for a user to think about this? To me it makes sense to leave this off by default and let the user know they can enable it in the docs.

Making more parameters optional will reduce the operator's "configuration footprint" and make it easier for users to evaluate the operator, without affecting its flexibility.

For inspiration, here is what the official [example](https://github.com/coreos/prometheus-operator/tree/master/example/rbac/prometheus) for the Prometheus operator looks like:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    prometheus: prometheus
spec:
  replicas: 2
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager
      port: web
```

And here is an especially minimalist [example](https://github.com/oracle/mysql-operator/blob/master/examples/cluster/cluster.yaml) from the MySQL operator:

```yaml
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql
```
