### ISSUE TITLE
[BUG] CRDs not installed on Subscription apply

### ISSUE THREAD

**Issue by adomenech73** [instaclustr/cassandra-operator#418]
**Describe the bug**

The Custom Resource Definitions (CRDs) for the Cassandra operator are not being installed, despite the installation job running successfully. The job logs show that the CRD files are being read, but when listing the available CRDs in the cluster, the Cassandra-related CRDs are not present.

**To Reproduce**

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cassandra-operator-subscription
  namespace: data-services
spec:
  channel: alpha
  name: cassandra-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
```

1. Apply the Cassandra operator subscription
2. Wait for the installation job to complete
3. Check the job logs, which show CRD files being read
4. List the CRDs in the cluster
5. Observe that Cassandra-related CRDs are missing

**Expected behavior**
After the installation job completes, the Cassandra-related CRDs (`cassandrabackups.cassandraoperator.instaclustr.com`, `cassandraclusters.cassandraoperator.instaclustr.com`, `cassandradatacenters.cassandraoperator.instaclustr.com`) should be present when listing CRDs in the cluster.

**Environment**
- OS: MacOsx: 14.6.1 > Colima: 0.8.1 arch: x86_64 runtime:docker > Kind: v0.25.0
- Kubernetes version: v1.31.2
- `kubectl version`: v1.31.3
- Go version: go version go1.23.2 darwin/arm64
- Cassandra version: cassandra-operator.v2.0.0

**Additional context**
- Perhaps I'm missing something.
- As workaround I can apply manually the creation of the CRDs from the deploy folder.
- Apple Silicon Hardware with x86 emulation.
